version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: apitizers_DB
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'YourStrong!Passw0rd'
    ports:
      - '1433:1433'
    volumes:
      - ./mssql_data:/var/opt/mssql/data
      - ./mssql_logs:/var/opt/mssql/log
      - ./mssql_secrets:/var/opt/mssql/secrets